 ###############################################################################################################
#              _                               _    _____                           _____ _                     # 
#     /\      | |                             | |  / ____|                         / ____| |                    #
#    /  \   __| |_   ____ _ _ __   ___ ___  __| | | (___   ___ _ __ ___  ___ _ __ | (___ | |__   __ _ _ __ ___  # 
#   / /\ \ / _` \ \ / / _` | '_ \ / __/ _ \/ _` |  \___ \ / __| '__/ _ \/ _ \ '_ \ \___ \| '_ \ / _` | '__/ _ \ # 
#  / ____ \ (_| |\ V / (_| | | | | (_|  __/ (_| |  ____) | (__| | |  __/  __/ | | |____) | | | | (_| | | |  __/ #
# /_/    \_\__,_| \_/ \__,_|_| |_|\___\___|\__,_| |_____/ \___|_|  \___|\___|_| |_|_____/|_| |_|\__,_|_|  \___  #
#                                                                                                               #
 ###############################################################################################################
 

 
#DO NOT CHANGE!
Config_Version: 0.8


#The prefix before most messages. (Supports colours)
Prefix: "&6[Server] &f"
#The message the user receives when tries to move.
Freeze_Message:
    - "Line 1"
    - "Line 2"
    - "Line &63"
    - "Supports colour codes &6:&4D"
#Use {USER} for targets username and {DISPLAY_NAME} for targets display name
Command_On_Leave: "ban {USER} Don't leave!"
#The amount of time the target has to get Screenshared 
#before the command CommandOnTimeDone command gets executed
#In ticks 20 ticks = 1 second
#1,200 ticks = 1 minut
#6,000 ticks = 5 minuts
#12,000 ticks = 10 minuts
TimeToJoinScreenShare: '120'
#When the TimeToJoinScreenShare time has passed this command will be run
#Use {USER} for targets username and {DISPLAY_NAME} for targets display name
#Use {TIME} For time that has passed
CommandOnTimeDone: "ban {USER} You did not join our Discord"
#Unfreeze the player when TimeToJoinScreenShare's time has passed
UnFreezePlayerOnTimeDone: true
#Execute the command stated at Command_On_Leave's command when a player leaves
ExecuteCommandOnLeave: true
    
    